doc.type.html
script
this.img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=document getelementbyid(header)
src.appendchild(this.img)
filename=covidstrings19.js
java.awt graphics 
<div id=header></div>
audio=new audio(audio_file mp3)
audio.play 
random button
new button (set random color)
option button
new  button (change color)
public fun with graphics()
color panel=new  panel();
this add (panel,center)
button panel
new  panel (flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
random r= newrandom();
colorpanel.setbackground(new color(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),(rnextint(13)(rnextint(13),(rnextInt(13),(rnextint(13)))
num teams
total players= players per team
if players per team=zero
return zero
else 
return math floor total players/players per team
teamsgrouping=(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)
buttonpanel.add(optionbutton);
optionbutton.add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
color m=jcolorchooser.showdialog(funwithgraphics.this)
if(multi!=null)
color panel set.background(multi)
this.add(buttonpanel,borderlayout.south)
public static main(string [] args)
jframe f = new covid strings19()
f.set title(covid strings19)
f.set default closeoperation(exit_on_close);
f.setsize
f.set visible(true);
<label id=lblscore>zero</label>
score=zero
if (mult == x*y)
[non-concatenated]
score+=ten
else:
score-=ten
if (mult ==x*y)
[concatenated]
score+=twenty
else:
score-=twenty
lblscore=document.getelementbyid(lblscore)
lbl.score.inner html=score
public actionperformed(action event e) 
system.out print.in (next button clicked)
frame.add(next button);
frame set visible true
object {a:one,b:two,c:three,d:four,e:five,f:six,g:seven,h:eight}
keys object keys(team)
entries object entries(obj);
value object= [team color]
covidstringsteamlist19=[black night riders ,green peacemakers ,burgundy rebuilders,indigo isos,red protein spikers,yellow moxie,violet relivers,orange rna messengers]
covid strings phraselist19=[non-concatenated strings
"the cdc on the other hand says the current wave is the second largest"
"one map might have predicted some of the hotspots"
"the question though is should you still be worried about it"?
"lifestyle though can help prevent long covid"
"andrew huberman is wrong on whether you should take both flu and covid shots"
"chinas post covid population collapse however is a lot more murky when it comes to hard data"
"from a new cold war perspective this could be some good news long term"
"inflation though could be a major wildcard both in the past and future" 
concatenated strings
"the"+"great"+"resignation"+"is"+"in"+"terms"+"of"+"economic"+"democracy"+"a"+"good"+"sign"
"in"+"terms"+"of"+"covid"+"democracy"+"there"+"is"+"more"+"freedom"+"of"+"movement"+"but"+"there"+"are"+"more"+"flawed"+"tests"
"at"+"least"+"this"+"will"+"be"+"over"+"soon"+"is"+"for"+"covid"+"and"+"hopefully"+"not"+"for"+"democracy"
"its"+"more"+"likely"+"that"+"more"+"bat"+"viruses"+"can"+"cause"+"another"+"pandemic"
"this"+"is"+"even"+"more"+"important"+"when"+"considering"+"that"+"covid"+"itself"+"was"+"caused"+"by"+"bats"
"this"+"also"+"means"+"more"+"research"+"on"+"bats"+"ability"+"to"+"spread"+"disease"
"covid"+"research"+"though"+"should"+"also"+"extend"+"to"+"long"+"covid"
"this"+"includes"+"research"+"and"+"trials"+"for"+"treatments"]
covid strings19 scrambled phraseslist=[non-concatenated "rachreas tab irusevs","gresalt veaw cesdon","nolg ovicd","ocdiv"+"emcorady","ocdiv"+"aterg"+"naitonesigr"]
covid strings19 multiplechoicelist=[1:a jojo siwa b the cdc c russian military bloggers d the nih,2:a democracy b authoritarianism c freedom house rankings d call of duty,3:a wizard b actuary c map d bill to kick trump off the ballot,4:a happy b worried c spaced out d thinking,5:a stock market reaching40 thousand b trumps new republican threat c great resignation d the alphabet soup agencies,6:a lifestyle b your mother c republicans stopping carrying putins water d common sense,7:a nuclear winter b winter is coming c this will be over soon d eternal darkness,
8:a rsv b hantavirus c norovirus d covid,9:a bat viruses b integration of people from nature c alien viruses d extreme snowboarding,10:a chinas b east timors c sri lanka d russias,11:a zz key b the american bar association c bats d an aardvark,12:a new cold war b hot peace c end of history d1980s,13:a skepticism b research c looking back d blind faith,14:a inflation b shrinkflation c sharkflation d shaqflation,
15:a short b medium  c long d russias election of,16:a tribulations b trials c russian activists fighting the kremlin d russian military cover-ups           
covid strings19 math problemslist =[ non-concatenated"inflation though could be a wildcard in both the past and future","if a graph showed a line of inflation with a slope of5 if the point in which the lines y intercept exists is at(0,1) what is the y coordinate if the x coordinate is9.5"?,"if the same graph were reflected along the x axis what would the resulting points be"?,"if the points from the previous question got reflected off the y axis at the same angle what would the new points be"?, "if the previous points got rotated 270 degrees clockwise what would the resulting points be"?,"if the first point in the solution of the previous problem was rotated180 degrees counterclockwise what would the result be"?,
concatenated "if"+"88"+"percent"+"view"+"the"+"great"+"resignation"+"as"+"a"+"positive"+"step"+"for"+"america"+"how"+"many"+"dont"?,"if"+"79"+"percent"+"strongly"+"believe"+"this"+"what"+"percent"+"is"+"mild"?,"if"+"the"+"margin"+"of"+"error"+"is"+"5.01"+"percent"+"what"+"is"+"the"+"range"?,"if"+"49"+"percent"+"believe"+"the"+"cdcs"+"claim"+"that"+"the"+"current"+"covid"+"wave"+"is"+"the"+"second"+"largest"+"how"+"many"+"dont"?,"if"+"36"+"percent"+"strongly"+"believe"+"this"+"how"+"many"+"are"+"mild"?,"if"+"the"+"margin"+"of"+"error"+"is"+"5.06"+"percent"+"what"+"is"+"the"+"range"?]
userin.select team
import meta.
class myclass
constructor(non-concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple Choice
else
prompt 
log
myclass=new.myclass(concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
import syntax 
chart js 
def gradient
id=mygradient
gradientunits=userspaceonuse
x1=0
y1=1
x2=9.5
y2=50.5
stop offset=0 stop-color=ff0000
stop offset=1 stop color=0000ff
<lineargradient>
<filter
id=linear1
filterunits=objectboundingbox
x=0%
y=0%
width=100%
height=100%
<fecomponenttransfer>
<fefunccovidstrings  type=linear slope>=1
transformationlist=[reflection,rotation,translation]
if reflection==x axis:
shift x axis
else:
remain
if rotation==270 degrees clockwise:
shift270 degrees clockwise
else:
remain
if rotation==180degrees:
shift180degrees
else:
remain 
public.boolean isscramble
if (s1.length())!=s2.length(),s3.length(),s4.length(),or s5.length()
return false
if (s1.length()) ==s2, s3, s4, or s5 length
return True
char[] arr1= s1.tochararray
char [] arr2= s2.tochararray
char [] arr3=s3.tochararray
arrays.sort(arr1)
arrays.sort(arr2)
arrays.sort(arr3)
if(!new string(arr1).equals(new string(arr2)))
return false
for(int i=1; i<s1.length();i++)}
string s11=s1.substring(0,i)
strings12=s1.substring(i,s1.length());
strings21=s2.substring(0,i)
string22=s2.substring(0,s2.length()-i);
string23=s2.substring(0,s2.length()-i ());
string31=s3.substring(0,i)
string32=s3.substring(0,s3.length()-i)
string33=s3.substring(0,s3.length()-i());
string41=s4.substring(0,i)
string42=s4.substring(0,s4.length()-i);
string43=s4.substring(0,s4.length()-i());
string51=s5.substring(0,i)
string52=s5.substring(0,s5.length()-i);
if selectedanswer=not correct
return false
else 
return true
if selectedanswer=correct:
return true
else:
return false
answer checker
scanner=new scanner(system.in)
string correct answer
string useranswer=scanner.nextline()
if useranswer.equals(correctanswer)
system.out.print.in(correct)
else:
system.out.printin(incorrect)
scanner.close
check winner:
if winner==true:
log(the winner is)
if winner==false:
log(no winner yet)
if users team wins covid strings19 
console log users team wins covid strings19 
else
return game over
return filename

