doc.type html
script
html
head
utf8
viewportcontent=width=device-width,initial-scale=one
title covid strings19 first round bracket
filename=covid strings19 first round.js
first round=(highest overall seed ,second highest seed third highest seed first middle seed, second middle seed,  third lowest seed ,second lowest seed,lowest overall seed)
highest overall seed =seed1
second highest seed=seed2
third highest seed=seed3
firstmiddleseed=seed4
second middle seed =seed5
third lowest seed= seed6
second lowest seed =seed7
lowest overall seed =seed8
covidstrings teamlist19=[black,green,burgundy,indigo,red,yellow,violet,orange]
creatematchup(orange versus black)
creatematchup(red versus indigo)
creatematchup(violet versus green)
creatematchup(yellow versus burgundy)
document.createelement 
matchupdiv.classname=(matchup)
matchupdiv.innerHTML =[matchup]
rounddiv.appendchild(matchup)
for (i in covid strings first round)
round div=create element
round div class name=covid strings19 first round
bracket.appendchild(round div)
if(event.target.covid strings seed list.contains(matchup))
event.target.covid strings seed list.toggle
else:
addmatchup
java util.scanner
java.util
questions[]questions=
question1
question2
question3
question4
question5
question6
question7
question8
question9
question10
question11
question12
question13
question14
question15
if selectedanswer==correct:
return true
else:
return false
advancingteam=slice(current teams)
declarewinner
result=declarewinner(team1 score, team2 score)
if black score>=forty:
console.log(black night riders win)
else:
console.log(orange rna messengers win)
if indigo score>=forty:
console.log(indigo isos win)
else:
console.log(red protein spikers win)
if green score>=forty:
console.log(green peacemakers win)
else:
console.log(violet relivers win)
if burgundy score>=forty:
console.log(burgundy rebuilders win)
else:
console.log(yellow moxie wins)
return filename
